name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "🎉 Thanks for opening your first issue! We’re happy to have you here and look forward to your contributions."
        pr-message: "🚀 Thanks for submitting your first pull request! We appreciate your contribution and will review it shortly."
